// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.0
// source: api/services_external.proto

package services_external

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_api_services_external_proto protoreflect.FileDescriptor

var file_api_services_external_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x67, 0x0a, 0x17, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x14, 0x49, 0x73, 0x41, 0x6e, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_api_services_external_proto_goTypes = []interface{}{
	(*emptypb.Empty)(nil),        // 0: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil), // 1: google.protobuf.BoolValue
}
var file_api_services_external_proto_depIdxs = []int32{
	0, // 0: ExternalServicesService.IsAnyServerAvailable:input_type -> google.protobuf.Empty
	1, // 1: ExternalServicesService.IsAnyServerAvailable:output_type -> google.protobuf.BoolValue
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_services_external_proto_init() }
func file_api_services_external_proto_init() {
	if File_api_services_external_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_services_external_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_external_proto_goTypes,
		DependencyIndexes: file_api_services_external_proto_depIdxs,
	}.Build()
	File_api_services_external_proto = out.File
	file_api_services_external_proto_rawDesc = nil
	file_api_services_external_proto_goTypes = nil
	file_api_services_external_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExternalServicesServiceClient is the client API for ExternalServicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExternalServicesServiceClient interface {
	IsAnyServerAvailable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
}

type externalServicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalServicesServiceClient(cc grpc.ClientConnInterface) ExternalServicesServiceClient {
	return &externalServicesServiceClient{cc}
}

func (c *externalServicesServiceClient) IsAnyServerAvailable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, "/ExternalServicesService/IsAnyServerAvailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServicesServiceServer is the server API for ExternalServicesService service.
type ExternalServicesServiceServer interface {
	IsAnyServerAvailable(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error)
}

// UnimplementedExternalServicesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExternalServicesServiceServer struct {
}

func (*UnimplementedExternalServicesServiceServer) IsAnyServerAvailable(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAnyServerAvailable not implemented")
}

func RegisterExternalServicesServiceServer(s *grpc.Server, srv ExternalServicesServiceServer) {
	s.RegisterService(&_ExternalServicesService_serviceDesc, srv)
}

func _ExternalServicesService_IsAnyServerAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServiceServer).IsAnyServerAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExternalServicesService/IsAnyServerAvailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServiceServer).IsAnyServerAvailable(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExternalServicesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExternalServicesService",
	HandlerType: (*ExternalServicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAnyServerAvailable",
			Handler:    _ExternalServicesService_IsAnyServerAvailable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services_external.proto",
}
