// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package services_external

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExternalServicesServiceClient is the client API for ExternalServicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalServicesServiceClient interface {
	IsAnyServerAvailable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
}

type externalServicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalServicesServiceClient(cc grpc.ClientConnInterface) ExternalServicesServiceClient {
	return &externalServicesServiceClient{cc}
}

func (c *externalServicesServiceClient) IsAnyServerAvailable(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, "/ExternalServicesService/IsAnyServerAvailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServicesServiceServer is the server API for ExternalServicesService service.
// All implementations must embed UnimplementedExternalServicesServiceServer
// for forward compatibility
type ExternalServicesServiceServer interface {
	IsAnyServerAvailable(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error)
	mustEmbedUnimplementedExternalServicesServiceServer()
}

// UnimplementedExternalServicesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExternalServicesServiceServer struct {
}

func (UnimplementedExternalServicesServiceServer) IsAnyServerAvailable(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAnyServerAvailable not implemented")
}
func (UnimplementedExternalServicesServiceServer) mustEmbedUnimplementedExternalServicesServiceServer() {
}

// UnsafeExternalServicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalServicesServiceServer will
// result in compilation errors.
type UnsafeExternalServicesServiceServer interface {
	mustEmbedUnimplementedExternalServicesServiceServer()
}

func RegisterExternalServicesServiceServer(s grpc.ServiceRegistrar, srv ExternalServicesServiceServer) {
	s.RegisterService(&ExternalServicesService_ServiceDesc, srv)
}

func _ExternalServicesService_IsAnyServerAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServiceServer).IsAnyServerAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExternalServicesService/IsAnyServerAvailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServiceServer).IsAnyServerAvailable(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalServicesService_ServiceDesc is the grpc.ServiceDesc for ExternalServicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalServicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ExternalServicesService",
	HandlerType: (*ExternalServicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAnyServerAvailable",
			Handler:    _ExternalServicesService_IsAnyServerAvailable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services_external.proto",
}
